CONVERT_TO = liatris

VIA_ENABLE = yes
VIAL_ENABLE = yes

# BACKLIGHT_ENABLE = yes
# BACKLIGHT_BREATHING_ENABLE = yes

RGBLIGHT_ENABLE = yes

OLED_ENABLE = yes

TAP_DANCE_ENABLE = yes
ENCODER_MAP_ENABLE = yes
COMBO_ENABLE		= yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

MOUSEKEY_ENABLE		= no
QMK_SETTINGS		= no
KEY_OVERRIDE_ENABLE	= no

CAPS_WORD_ENABLE	= yes